// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnjhiltssilzsovsauxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuamhpbHRzc2lsenNvdnNhdXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NzE0ODMsImV4cCI6MjA2MTQ0NzQ4M30.bCDgxhrRsxo-F4OIjoCh4RmDZSyJqjq64lNlCNtGP6w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);